services:
  initialize:
    image: busybox
    command: chown -Rc ${ZIGGY_UID:-1000} /persistent
    user: root
    environment:
      HOME: /persistent
      # PFXLOG_NO_JSON: "true"
    volumes:
    - ./persistent:/persistent
  quickstart:
    depends_on:
      initialize:
        condition: service_completed_successfully
    image: ${ZITI_QUICK_IMAGE:-docker.io/openziti/ziti-cli}:${ZITI_QUICK_TAG:-latest}
    build:
      context: ${ZITI_SRC_ROOT:-../../../} 
      dockerfile: ./quickstart/docker/minimal/Dockerfile
      args: {}
    entrypoint:
    - bash
    - -euc
    - |
      if [[ -d /persistent/db ]]
      then
        echo "INFO: not initializing. Delete state directory ./persistent/ to reset quickstart."
        ZITI_CMD+=" --already-initialized"
      else
        echo "INFO: initializing quickstart in state directory ./persistent/"
        ZITI_CMD+=" --ctrl-address 127.0.0.1"\
      " --router-address 127.0.0.1"\
      " --password ${ZITI_PWD:-admin}"
      fi
      echo "DEBUG: run command is: ziti $${@} $${ZITI_CMD}"
      exec ziti "$${@}" $${ZITI_CMD}
    command: -- edge quickstart --home /persistent
    user: ${ZIGGY_UID:-1000}
    environment:
      HOME: /persistent
      PFXLOG_NO_JSON: "true"
    volumes:
    - ./persistent:/persistent
    ports:
    - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}:${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
    - ${ZITI_INTERFACE:-0.0.0.0}:${ZITI_ROUTER_PORT:-3022}:${ZITI_ROUTER_PORT:-3022}
